# Generated by Django 5.0.1 on 2024-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='toonname',
        ),
        migrations.AddField(
            model_name='entry',
            name='players',
            field=models.ManyToManyField(to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='avatarId',
            field=models.CharField(max_length=255),
        ),
    ]
